app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin:
    resource: '@AppBundle/Resources/config/routing.yml'

admin_applics:
    resource: '@ApplicBundle/Resources/config/routing.yml'

user:
    resource: '@UserBundle/Resources/config/routing.yml'
