security:
    encoders:
        user_provider:
            class: UserBundle\Entity\User
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        #ROLE_ADMIN: ROLE_USER
        ROLE_ROOT: ROLE_USER

    providers:
        user_provider:
            entity:
                class: UserBundle:User
                property: email

    firewalls:
        user:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /
                provider: user_provider
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/cron, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN}
