page_callback:
  path: /callback
  defaults: { _controller: AppBundle:Page:getCallBack}

page_services_documents:
  path: /services/documents
  defaults: { _controller: AppBundle:Page:getServiceDocuments}
