admin_index:
  path: /admin/
  defaults: { _controller: AppBundle:Admin:index}

admin_settings:
  path: /admin/settings/
  defaults: { _controller: AppBundle:Admin:settings}

admin_settings_design:
  path: /admin/settings/design
  defaults: { _controller: AppBundle:Admin:settingsDesign}

admin_settings_revert:
  path: /admin/settings/revert/{id}/
  defaults: { _controller: AppBundle:Admin:revertConfig}

admin_court_practices_all:
  path: /admin/practices/
  defaults: { _controller: AppBundle:Admin:courtPracticeViewAll}

admin_court_practices_add:
  path: /admin/practices/add
  defaults: { _controller: AppBundle:Admin:courtPracticeAdd}
