page_callback:
  path: /callback/
  defaults: { _controller: AppBundle:Page:getCallBack}

page_services_documents:
  path: /services/documents/
  defaults: { _controller: AppBundle:Page:getServiceDocuments}

page_services_document:
  path: /services/documents/{id}/
  defaults: { _controller: AppBundle:Page:getServiceDocument}

page_works_family:
  path: /services/works/family/
  defaults: { _controller: AppBundle:Page:getWorksFamily}

page_works_service:
  path: /services/works/{workUrl}/
  defaults: { _controller: AppBundle:Page:getWorkPage}
